<header>

</header>

<main>

    <form class="formPage" action="" method="post" data-validation="true">
        <aside class="error-message hidden">
                <h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
                <p><?php echo $form->getErrorMessage(); ?></p>
        </aside>
        <fieldset>
            <h2>Se Connecter</h2>
            <ul>
                <li>
                    <label for="email">Email :</label><input type="text" name="email" data-required data-name="Email" data-type="email">
                </li>

                <li>
                    <label for="password"> Mot de Passe :</label><input type="password" data-required data-name="Mot de passe" name="password">
                </li>

                <li>
                    <input class="bouton" type="submit" name="add" value="Connexion">
                </li>
            </ul>
        </fieldset>
    </form>

</main>
